### ISSUE TITLE
oraswdb-install: wrong oracle_home with mixed Oracle Releases in db_homes_installed

### ISSUE THREAD

**Issue by Rendanic** [opitzconsulting/ansible-oracle#42]
The following task leads to an issue, when `db_homes_installed `has different Oracle-Releases.
The variable `oracle_home_db `is initialized for the 1st elemt in a loop of the included tasklist. The 2nd element inside the loop will use the result from the 1st element.
=> The unarchive is wrong.

```
db_homes_installed:
  - home: db19-si-ee
    apply_patches: True
    state: present
  - home: db18-si-ee
    apply_patches: True
    state: present
```

```
  - include_tasks: install-home-db.yml
    with_items:
        - "{{ db_homes_installed }}"
    loop_control:
      loop_var: dbh
    when: db_homes_installed is defined and dbh.state|lower == 'present'
    tags: oradbinstall,dbchopt
```

Solution:
All loops in the include_task files needs a refactoring. There is no need to loop over `db_homes_installed `inside the included file.
