### ISSUE TITLE
new role for configuration of oraclenet files

### ISSUE THREAD

**Issue by Rendanic** [opitzconsulting/ansible-oracle#49]
The current configuration of listener.ora, sqlnet.ora and tnsnames.ora will be moved into a new role for easier configuration in the future.
In a next step the role get the ability to configure listener for Oracle Restart and Grid-Infrastructure.

Change in `listener_installed`:
The listener_installed needs modifications, when a listener for Restart/GI is configured, because 'home' points to an ORACLE_HOME instead of CRS_HOME.

Example: (current)
```
listener_installed:
  - home: db19-si-ee
    listener_name: LISTENER1521
    state: present
```

Idea:
```
listener_installed:
  - has_listener: yes | default(no)
    listener_name: LISTENER1521
    state: present
```
